name: deploy_The_Greeting_Kata

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        continue-on-error: false
      
      - name: Execute push
        run: |
          dotnet nuget add source \
            --username StokicMarko \
            --password ${{ secrets.TOKEN }} \
            --store-password-in-clear-text \
            --name github "https://nuget.pkg.github.com/StokicMarko/index.json"

          dotnet nuget push "bin/Release/Greeting.1.0.${{ github.run_number }}.nupkg" \
            --api-key ${{ secrets.TOKEN }} \
            --source "github"

           
